import assert from 'node:assert/strict'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ channel: 'msedge', headless: true })
try {
  const context = await browser.newContext({ serviceWorkers: 'block' })
  const calls = []
  await context.route('**/*.supabase.co/**', route => {
    calls.push(route.request().postDataJSON())
    return route.fulfill({ status: 200, contentType: 'application/json', body: 'true' })
  })
  const page = await context.newPage()
  const fixture = 'http://127.0.0.1:5173/tests/fixtures/blog-consent.html'
  await page.goto(fixture + '?local=1')
  await page.getByRole('button', { name: '允许统计', exact: true }).waitFor()
  await page.waitForTimeout(1500)
  assert.equal(calls.length, 0)
  await page.getByRole('button', { name: '允许统计', exact: true }).click()
  await page.waitForTimeout(1500)
  assert.equal(calls.length, 1)
  assert.equal(calls[0].p_path, '/')
  assert.match(calls[0].p_visitor, /^[0-9a-f-]{36}$/)
  await page.getByRole('button', { name: '隐私设置' }).click()
  await page.getByRole('button', { name: '不允许', exact: true }).click()
  assert.equal(await page.evaluate(() => localStorage.getItem('clc_blog_visitor')), null)
  await page.goto(fixture + '?local=1')
  await page.waitForTimeout(1500)
  assert.equal(calls.length, 1)
  await page.evaluate(() => localStorage.setItem('clc_blog_statistics', 'allowed'))
  await page.goto(fixture)
  await page.waitForTimeout(1500)
  assert.equal(calls.length, 1, 'local development excluded')
  await page.goto(fixture + '?local=1&path=/blog-admin')
  await page.waitForTimeout(1500)
  assert.equal(calls.length, 1, 'private paths excluded')
  await context.addInitScript(() => Object.defineProperty(navigator, 'globalPrivacyControl', { value: true }))
  await page.goto(fixture + '?local=1')
  await page.waitForTimeout(1500)
  assert.equal(calls.length, 1, 'GPC excluded')
  console.log('Analytics consent, rejection, withdrawal, local/private exclusion and browser privacy signal passed.')
} finally { await browser.close() }
